#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFarmacia")]
	public partial class BDSistemaFarmaciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertFactura_Detalle(Factura_Detalle instance);
    partial void UpdateFactura_Detalle(Factura_Detalle instance);
    partial void DeleteFactura_Detalle(Factura_Detalle instance);
    partial void InsertMedicamento(Medicamento instance);
    partial void UpdateMedicamento(Medicamento instance);
    partial void DeleteMedicamento(Medicamento instance);
    partial void InsertPromociones(Promociones instance);
    partial void UpdatePromociones(Promociones instance);
    partial void DeletePromociones(Promociones instance);
    #endregion
		
		public BDSistemaFarmaciaDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.SistemaFarmaciaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDSistemaFarmaciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSistemaFarmaciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSistemaFarmaciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDSistemaFarmaciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administrador
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Factura
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Factura_Detalle> Factura_Detalle
		{
			get
			{
				return this.GetTable<Factura_Detalle>();
			}
		}
		
		public System.Data.Linq.Table<Medicamento> Medicamento
		{
			get
			{
				return this.GetTable<Medicamento>();
			}
		}
		
		public System.Data.Linq.Table<Promociones> Promociones
		{
			get
			{
				return this.GetTable<Promociones>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarMedicamento")]
		public int SP_ActualizarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedicamento", DbType="Int")] System.Nullable<int> idMedicamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enpaque", DbType="VarChar(20)")] string enpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Presentacion", DbType="VarChar(15)")] string presentacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaVencimiento", DbType="DateTime")] System.Nullable<System.DateTime> fechaVencimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string viaAdministracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Almacenamiento", DbType="VarChar(15)")] string almacenamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especificacion", DbType="VarChar(100)")] string especificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPromocion", DbType="Int")] System.Nullable<int> idPromocion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMedicamento, nombre, enpaque, cantidad, presentacion, fechaVencimiento, viaAdministracion, almacenamiento, especificacion, precio, idPromocion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarMedicamento")]
		public int SP_EliminarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedicamento", DbType="Int")] System.Nullable<int> idMedicamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMedicamento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarMedicamento")]
		public int SP_InsertarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedicamento", DbType="Int")] System.Nullable<int> idMedicamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enpaque", DbType="VarChar(20)")] string enpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Presentacion", DbType="VarChar(15)")] string presentacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaVencimiento", DbType="DateTime")] System.Nullable<System.DateTime> fechaVencimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string viaAdministracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Almacenamiento", DbType="VarChar(15)")] string almacenamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especificacion", DbType="VarChar(100)")] string especificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPromocion", DbType="Int")] System.Nullable<int> idPromocion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMedicamento, nombre, enpaque, cantidad, presentacion, fechaVencimiento, viaAdministracion, almacenamiento, especificacion, precio, idPromocion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarAdministrador")]
		public int SP_ActualizarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(100)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(40)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(40)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(45)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(30)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(30)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, contrasena, cedula, nombres, apellidos, telefono, email, tipo, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarAdministrador")]
		public int SP_EliminarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarAdministrador")]
		public int SP_InsertarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(100)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(40)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(40)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(45)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(30)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(30)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, contrasena, cedula, nombres, apellidos, telefono, email, tipo, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarAdministradorFiltro")]
		public ISingleResult<SP_ListarAdministradorFiltroResult> SP_ListarAdministradorFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarAdministradorFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarCliente")]
		public int SP_ActualizarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(40)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(30)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, nombre, apellido, correo, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCliente")]
		public int SP_EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCliente")]
		public int SP_InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(40)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(30)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, nombre, apellido, correo, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarClienteFiltro")]
		public ISingleResult<SP_ListarClienteFiltroResult> SP_ListarClienteFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarClienteFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarFactura")]
		public int SP_ActualizarFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFactura", DbType="DateTime")] System.Nullable<System.DateTime> fechaFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, total, fechaFactura, idCliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarFactura")]
		public int SP_EliminarFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarFactura")]
		public int SP_InsertarFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFactura", DbType="DateTime")] System.Nullable<System.DateTime> fechaFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, total, fechaFactura, idCliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarFactura_Detalle")]
		public int SP_InsertarFactura_Detalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedicamento", DbType="Int")] System.Nullable<int> idMedicamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subtotal", DbType="Money")] System.Nullable<decimal> subtotal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, idMedicamento, cantidad, subtotal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarFactura_Detalle")]
		public int SP_EliminarFactura_Detalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarFactura_Detalle")]
		public int SP_ActualizarFactura_Detalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedicamento", DbType="Int")] System.Nullable<int> idMedicamento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subtotal", DbType="Money")] System.Nullable<decimal> subtotal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, idMedicamento, cantidad, subtotal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarPromociones")]
		public int SP_ActualizarPromociones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPromocion", DbType="Int")] System.Nullable<int> idPromocion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(40)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Porcentaje", DbType="Decimal(18,0)")] System.Nullable<decimal> porcentaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPromocion, tipo, porcentaje);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarPromociones")]
		public int SP_EliminarPromociones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPromocion", DbType="Int")] System.Nullable<int> idPromocion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPromocion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarPromociones")]
		public int SP_InsertarPromociones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPromocion", DbType="Int")] System.Nullable<int> idPromocion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(40)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Porcentaje", DbType="Decimal(18,0)")] System.Nullable<decimal> porcentaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPromocion, tipo, porcentaje);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarFacturaFiltro")]
		public ISingleResult<SP_ListarFacturaFiltroResult> SP_ListarFacturaFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="Int")] System.Nullable<int> valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarFacturaFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarFactura_DetalleFiltro")]
		public ISingleResult<SP_ListarFactura_DetalleFiltroResult> SP_ListarFactura_DetalleFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="Int")] System.Nullable<int> valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarFactura_DetalleFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarMedicamentoFiltro")]
		public ISingleResult<SP_ListarMedicamentoFiltroResult> SP_ListarMedicamentoFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarMedicamentoFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarPromocionesFiltro")]
		public ISingleResult<SP_ListarPromocionesFiltroResult> SP_ListarPromocionesFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarPromocionesFiltroResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Contrasena;
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Telefono;
		
		private string _Email;
		
		private string _Tipo;
		
		private string _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Administrador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCliente;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Cedula;
		
		private EntitySet<Factura> _Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    #endregion
		
		public Cliente()
		{
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Factura", ThisKey="IdCliente", OtherKey="IdCliente")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFactura;
		
		private decimal _Total;
		
		private System.DateTime _FechaFactura;
		
		private int _IdCliente;
		
		private EntitySet<Factura_Detalle> _Factura_Detalle;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    partial void OnTotalChanging(decimal value);
    partial void OnTotalChanged();
    partial void OnFechaFacturaChanging(System.DateTime value);
    partial void OnFechaFacturaChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    #endregion
		
		public Factura()
		{
			this._Factura_Detalle = new EntitySet<Factura_Detalle>(new Action<Factura_Detalle>(this.attach_Factura_Detalle), new Action<Factura_Detalle>(this.detach_Factura_Detalle));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money NOT NULL")]
		public decimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFactura", DbType="DateTime NOT NULL")]
		public System.DateTime FechaFactura
		{
			get
			{
				return this._FechaFactura;
			}
			set
			{
				if ((this._FechaFactura != value))
				{
					this.OnFechaFacturaChanging(value);
					this.SendPropertyChanging();
					this._FechaFactura = value;
					this.SendPropertyChanged("FechaFactura");
					this.OnFechaFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Factura_Detalle", Storage="_Factura_Detalle", ThisKey="IdFactura", OtherKey="IdFactura")]
		public EntitySet<Factura_Detalle> Factura_Detalle
		{
			get
			{
				return this._Factura_Detalle;
			}
			set
			{
				this._Factura_Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Cliente", ThisKey="IdCliente", OtherKey="IdCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._IdCliente = value.IdCliente;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura_Detalle(Factura_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Factura_Detalle(Factura_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura_Detalle")]
	public partial class Factura_Detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFactura;
		
		private int _IdMedicamento;
		
		private int _Cantidad;
		
		private decimal _Subtotal;
		
		private EntityRef<Factura> _Factura;
		
		private EntityRef<Medicamento> _Medicamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    partial void OnIdMedicamentoChanging(int value);
    partial void OnIdMedicamentoChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnSubtotalChanging(decimal value);
    partial void OnSubtotalChanged();
    #endregion
		
		public Factura_Detalle()
		{
			this._Factura = default(EntityRef<Factura>);
			this._Medicamento = default(EntityRef<Medicamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedicamento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMedicamento
		{
			get
			{
				return this._IdMedicamento;
			}
			set
			{
				if ((this._IdMedicamento != value))
				{
					if (this._Medicamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMedicamentoChanging(value);
					this.SendPropertyChanging();
					this._IdMedicamento = value;
					this.SendPropertyChanged("IdMedicamento");
					this.OnIdMedicamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Money NOT NULL")]
		public decimal Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Factura_Detalle", Storage="_Factura", ThisKey="IdFactura", OtherKey="IdFactura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Factura_Detalle.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Factura_Detalle.Add(this);
						this._IdFactura = value.IdFactura;
					}
					else
					{
						this._IdFactura = default(int);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Medicamento_Factura_Detalle", Storage="_Medicamento", ThisKey="IdMedicamento", OtherKey="IdMedicamento", IsForeignKey=true)]
		public Medicamento Medicamento
		{
			get
			{
				return this._Medicamento.Entity;
			}
			set
			{
				Medicamento previousValue = this._Medicamento.Entity;
				if (((previousValue != value) 
							|| (this._Medicamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Medicamento.Entity = null;
						previousValue.Factura_Detalle.Remove(this);
					}
					this._Medicamento.Entity = value;
					if ((value != null))
					{
						value.Factura_Detalle.Add(this);
						this._IdMedicamento = value.IdMedicamento;
					}
					else
					{
						this._IdMedicamento = default(int);
					}
					this.SendPropertyChanged("Medicamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medicamento")]
	public partial class Medicamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMedicamento;
		
		private string _Nombre;
		
		private string _Enpaque;
		
		private int _Cantidad;
		
		private string _Presentacion;
		
		private System.DateTime _FechaVencimiento;
		
		private string _viaAdministracion;
		
		private string _Almacenamiento;
		
		private string _Especificacion;
		
		private decimal _Precio;
		
		private int _IdPromocion;
		
		private EntitySet<Factura_Detalle> _Factura_Detalle;
		
		private EntityRef<Promociones> _Promociones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMedicamentoChanging(int value);
    partial void OnIdMedicamentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEnpaqueChanging(string value);
    partial void OnEnpaqueChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnPresentacionChanging(string value);
    partial void OnPresentacionChanged();
    partial void OnFechaVencimientoChanging(System.DateTime value);
    partial void OnFechaVencimientoChanged();
    partial void OnviaAdministracionChanging(string value);
    partial void OnviaAdministracionChanged();
    partial void OnAlmacenamientoChanging(string value);
    partial void OnAlmacenamientoChanged();
    partial void OnEspecificacionChanging(string value);
    partial void OnEspecificacionChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnIdPromocionChanging(int value);
    partial void OnIdPromocionChanged();
    #endregion
		
		public Medicamento()
		{
			this._Factura_Detalle = new EntitySet<Factura_Detalle>(new Action<Factura_Detalle>(this.attach_Factura_Detalle), new Action<Factura_Detalle>(this.detach_Factura_Detalle));
			this._Promociones = default(EntityRef<Promociones>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedicamento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMedicamento
		{
			get
			{
				return this._IdMedicamento;
			}
			set
			{
				if ((this._IdMedicamento != value))
				{
					this.OnIdMedicamentoChanging(value);
					this.SendPropertyChanging();
					this._IdMedicamento = value;
					this.SendPropertyChanged("IdMedicamento");
					this.OnIdMedicamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enpaque", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Enpaque
		{
			get
			{
				return this._Enpaque;
			}
			set
			{
				if ((this._Enpaque != value))
				{
					this.OnEnpaqueChanging(value);
					this.SendPropertyChanging();
					this._Enpaque = value;
					this.SendPropertyChanged("Enpaque");
					this.OnEnpaqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presentacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Presentacion
		{
			get
			{
				return this._Presentacion;
			}
			set
			{
				if ((this._Presentacion != value))
				{
					this.OnPresentacionChanging(value);
					this.SendPropertyChanging();
					this._Presentacion = value;
					this.SendPropertyChanged("Presentacion");
					this.OnPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this.OnFechaVencimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaVencimiento = value;
					this.SendPropertyChanged("FechaVencimiento");
					this.OnFechaVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viaAdministracion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string viaAdministracion
		{
			get
			{
				return this._viaAdministracion;
			}
			set
			{
				if ((this._viaAdministracion != value))
				{
					this.OnviaAdministracionChanging(value);
					this.SendPropertyChanging();
					this._viaAdministracion = value;
					this.SendPropertyChanged("viaAdministracion");
					this.OnviaAdministracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Almacenamiento", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Almacenamiento
		{
			get
			{
				return this._Almacenamiento;
			}
			set
			{
				if ((this._Almacenamiento != value))
				{
					this.OnAlmacenamientoChanging(value);
					this.SendPropertyChanging();
					this._Almacenamiento = value;
					this.SendPropertyChanged("Almacenamiento");
					this.OnAlmacenamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especificacion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Especificacion
		{
			get
			{
				return this._Especificacion;
			}
			set
			{
				if ((this._Especificacion != value))
				{
					this.OnEspecificacionChanging(value);
					this.SendPropertyChanging();
					this._Especificacion = value;
					this.SendPropertyChanged("Especificacion");
					this.OnEspecificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPromocion", DbType="Int NOT NULL")]
		public int IdPromocion
		{
			get
			{
				return this._IdPromocion;
			}
			set
			{
				if ((this._IdPromocion != value))
				{
					if (this._Promociones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPromocionChanging(value);
					this.SendPropertyChanging();
					this._IdPromocion = value;
					this.SendPropertyChanged("IdPromocion");
					this.OnIdPromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Medicamento_Factura_Detalle", Storage="_Factura_Detalle", ThisKey="IdMedicamento", OtherKey="IdMedicamento")]
		public EntitySet<Factura_Detalle> Factura_Detalle
		{
			get
			{
				return this._Factura_Detalle;
			}
			set
			{
				this._Factura_Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promociones_Medicamento", Storage="_Promociones", ThisKey="IdPromocion", OtherKey="IdPromocion", IsForeignKey=true)]
		public Promociones Promociones
		{
			get
			{
				return this._Promociones.Entity;
			}
			set
			{
				Promociones previousValue = this._Promociones.Entity;
				if (((previousValue != value) 
							|| (this._Promociones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Promociones.Entity = null;
						previousValue.Medicamento.Remove(this);
					}
					this._Promociones.Entity = value;
					if ((value != null))
					{
						value.Medicamento.Add(this);
						this._IdPromocion = value.IdPromocion;
					}
					else
					{
						this._IdPromocion = default(int);
					}
					this.SendPropertyChanged("Promociones");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura_Detalle(Factura_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Medicamento = this;
		}
		
		private void detach_Factura_Detalle(Factura_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Medicamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Promociones")]
	public partial class Promociones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPromocion;
		
		private string _Tipo;
		
		private decimal _Porcentaje;
		
		private EntitySet<Medicamento> _Medicamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPromocionChanging(int value);
    partial void OnIdPromocionChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnPorcentajeChanging(decimal value);
    partial void OnPorcentajeChanged();
    #endregion
		
		public Promociones()
		{
			this._Medicamento = new EntitySet<Medicamento>(new Action<Medicamento>(this.attach_Medicamento), new Action<Medicamento>(this.detach_Medicamento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPromocion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPromocion
		{
			get
			{
				return this._IdPromocion;
			}
			set
			{
				if ((this._IdPromocion != value))
				{
					this.OnIdPromocionChanging(value);
					this.SendPropertyChanging();
					this._IdPromocion = value;
					this.SendPropertyChanged("IdPromocion");
					this.OnIdPromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Porcentaje", DbType="Decimal(18,0) NOT NULL")]
		public decimal Porcentaje
		{
			get
			{
				return this._Porcentaje;
			}
			set
			{
				if ((this._Porcentaje != value))
				{
					this.OnPorcentajeChanging(value);
					this.SendPropertyChanging();
					this._Porcentaje = value;
					this.SendPropertyChanged("Porcentaje");
					this.OnPorcentajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promociones_Medicamento", Storage="_Medicamento", ThisKey="IdPromocion", OtherKey="IdPromocion")]
		public EntitySet<Medicamento> Medicamento
		{
			get
			{
				return this._Medicamento;
			}
			set
			{
				this._Medicamento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Medicamento(Medicamento entity)
		{
			this.SendPropertyChanging();
			entity.Promociones = this;
		}
		
		private void detach_Medicamento(Medicamento entity)
		{
			this.SendPropertyChanging();
			entity.Promociones = null;
		}
	}
	
	public partial class SP_ListarAdministradorFiltroResult
	{
		
		private int _IdUsuario;
		
		private string _Contrasena;
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Telefono;
		
		private string _Email;
		
		private string _Tipo;
		
		private string _Estado;
		
		public SP_ListarAdministradorFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_ListarClienteFiltroResult
	{
		
		private int _IdCliente;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Cedula;
		
		public SP_ListarClienteFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class SP_ListarFacturaFiltroResult
	{
		
		private int _IdFactura;
		
		private decimal _Total;
		
		private System.DateTime _FechaFactura;
		
		private int _IdCliente;
		
		public SP_ListarFacturaFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money NOT NULL")]
		public decimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFactura", DbType="DateTime NOT NULL")]
		public System.DateTime FechaFactura
		{
			get
			{
				return this._FechaFactura;
			}
			set
			{
				if ((this._FechaFactura != value))
				{
					this._FechaFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
	}
	
	public partial class SP_ListarFactura_DetalleFiltroResult
	{
		
		private int _IdFactura;
		
		private int _IdMedicamento;
		
		private int _Cantidad;
		
		private decimal _Subtotal;
		
		public SP_ListarFactura_DetalleFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedicamento", DbType="Int NOT NULL")]
		public int IdMedicamento
		{
			get
			{
				return this._IdMedicamento;
			}
			set
			{
				if ((this._IdMedicamento != value))
				{
					this._IdMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Money NOT NULL")]
		public decimal Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this._Subtotal = value;
				}
			}
		}
	}
	
	public partial class SP_ListarMedicamentoFiltroResult
	{
		
		private int _IdMedicamento;
		
		private string _Nombre;
		
		private string _Enpaque;
		
		private int _Cantidad;
		
		private string _Presentacion;
		
		private System.DateTime _FechaVencimiento;
		
		private string _viaAdministracion;
		
		private string _Almacenamiento;
		
		private string _Especificacion;
		
		private decimal _Precio;
		
		private int _IdPromocion;
		
		public SP_ListarMedicamentoFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedicamento", DbType="Int NOT NULL")]
		public int IdMedicamento
		{
			get
			{
				return this._IdMedicamento;
			}
			set
			{
				if ((this._IdMedicamento != value))
				{
					this._IdMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enpaque", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Enpaque
		{
			get
			{
				return this._Enpaque;
			}
			set
			{
				if ((this._Enpaque != value))
				{
					this._Enpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presentacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Presentacion
		{
			get
			{
				return this._Presentacion;
			}
			set
			{
				if ((this._Presentacion != value))
				{
					this._Presentacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this._FechaVencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viaAdministracion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string viaAdministracion
		{
			get
			{
				return this._viaAdministracion;
			}
			set
			{
				if ((this._viaAdministracion != value))
				{
					this._viaAdministracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Almacenamiento", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Almacenamiento
		{
			get
			{
				return this._Almacenamiento;
			}
			set
			{
				if ((this._Almacenamiento != value))
				{
					this._Almacenamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especificacion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Especificacion
		{
			get
			{
				return this._Especificacion;
			}
			set
			{
				if ((this._Especificacion != value))
				{
					this._Especificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPromocion", DbType="Int NOT NULL")]
		public int IdPromocion
		{
			get
			{
				return this._IdPromocion;
			}
			set
			{
				if ((this._IdPromocion != value))
				{
					this._IdPromocion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarPromocionesFiltroResult
	{
		
		private int _IdPromocion;
		
		private string _Tipo;
		
		private decimal _Porcentaje;
		
		public SP_ListarPromocionesFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPromocion", DbType="Int NOT NULL")]
		public int IdPromocion
		{
			get
			{
				return this._IdPromocion;
			}
			set
			{
				if ((this._IdPromocion != value))
				{
					this._IdPromocion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Porcentaje", DbType="Decimal(18,0) NOT NULL")]
		public decimal Porcentaje
		{
			get
			{
				return this._Porcentaje;
			}
			set
			{
				if ((this._Porcentaje != value))
				{
					this._Porcentaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
