<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFarmacia" Class="BDSistemaFarmaciaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-JAENV44;Initial Catalog=SistemaFarmacia;Integrated Security=True" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="SistemaFarmaciaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrador" Member="Administrador">
    <Type Name="Administrador">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Factura" Member="Factura" ThisKey="IdCliente" OtherKey="IdCliente" Type="Factura" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Factura">
    <Type Name="Factura">
      <Column Name="IdFactura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FechaFactura" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Factura_Factura_Detalle" Member="Factura_Detalle" ThisKey="IdFactura" OtherKey="IdFactura" Type="Factura_Detalle" />
      <Association Name="Cliente_Factura" Member="Cliente" ThisKey="IdCliente" OtherKey="IdCliente" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Factura_Detalle" Member="Factura_Detalle">
    <Type Name="Factura_Detalle">
      <Column Name="IdFactura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdMedicamento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Factura_Factura_Detalle" Member="Factura" ThisKey="IdFactura" OtherKey="IdFactura" Type="Factura" IsForeignKey="true" />
      <Association Name="Medicamento_Factura_Detalle" Member="Medicamento" ThisKey="IdMedicamento" OtherKey="IdMedicamento" Type="Medicamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medicamento" Member="Medicamento">
    <Type Name="Medicamento">
      <Column Name="IdMedicamento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enpaque" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Presentacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FechaVencimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="viaAdministracion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Almacenamiento" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Especificacion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IdPromocion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Medicamento_Factura_Detalle" Member="Factura_Detalle" ThisKey="IdMedicamento" OtherKey="IdMedicamento" Type="Factura_Detalle" />
      <Association Name="Promociones_Medicamento" Member="Promociones" ThisKey="IdPromocion" OtherKey="IdPromocion" Type="Promociones" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promociones" Member="Promociones">
    <Type Name="Promociones">
      <Column Name="IdPromocion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Porcentaje" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Promociones_Medicamento" Member="Medicamento" ThisKey="IdPromocion" OtherKey="IdPromocion" Type="Medicamento" />
    </Type>
  </Table>
  <Function Name="dbo.SP_ActualizarMedicamento" Method="SP_ActualizarMedicamento">
    <Parameter Name="IdMedicamento" Parameter="idMedicamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Enpaque" Parameter="enpaque" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Presentacion" Parameter="presentacion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="FechaVencimiento" Parameter="fechaVencimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="viaAdministracion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Almacenamiento" Parameter="almacenamiento" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Especificacion" Parameter="especificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="IdPromocion" Parameter="idPromocion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarMedicamento" Method="SP_EliminarMedicamento">
    <Parameter Name="IdMedicamento" Parameter="idMedicamento" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarMedicamento" Method="SP_InsertarMedicamento">
    <Parameter Name="IdMedicamento" Parameter="idMedicamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Enpaque" Parameter="enpaque" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Presentacion" Parameter="presentacion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="FechaVencimiento" Parameter="fechaVencimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="viaAdministracion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Almacenamiento" Parameter="almacenamiento" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Especificacion" Parameter="especificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="IdPromocion" Parameter="idPromocion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarAdministrador" Method="SP_ActualizarAdministrador">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarAdministrador" Method="SP_EliminarAdministrador">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarAdministrador" Method="SP_InsertarAdministrador">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarAdministradorFiltro" Method="SP_ListarAdministradorFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarAdministradorFiltroResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ActualizarCliente" Method="SP_ActualizarCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarCliente" Method="SP_EliminarCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarCliente" Method="SP_InsertarCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarClienteFiltro" Method="SP_ListarClienteFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarClienteFiltroResult">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ActualizarFactura" Method="SP_ActualizarFactura">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="FechaFactura" Parameter="fechaFactura" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarFactura" Method="SP_EliminarFactura">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarFactura" Method="SP_InsertarFactura">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="FechaFactura" Parameter="fechaFactura" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarFactura_Detalle" Method="SP_InsertarFactura_Detalle">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdMedicamento" Parameter="idMedicamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Subtotal" Parameter="subtotal" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarFactura_Detalle" Method="SP_EliminarFactura_Detalle">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarFactura_Detalle" Method="SP_ActualizarFactura_Detalle">
    <Parameter Name="IdFactura" Parameter="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdMedicamento" Parameter="idMedicamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Subtotal" Parameter="subtotal" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarPromociones" Method="SP_ActualizarPromociones">
    <Parameter Name="IdPromocion" Parameter="idPromocion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Porcentaje" Parameter="porcentaje" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarPromociones" Method="SP_EliminarPromociones">
    <Parameter Name="IdPromocion" Parameter="idPromocion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarPromociones" Method="SP_InsertarPromociones">
    <Parameter Name="IdPromocion" Parameter="idPromocion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Porcentaje" Parameter="porcentaje" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarFacturaFiltro" Method="SP_ListarFacturaFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarFacturaFiltroResult">
      <Column Name="IdFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FechaFactura" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarFactura_DetalleFiltro" Method="SP_ListarFactura_DetalleFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarFactura_DetalleFiltroResult">
      <Column Name="IdFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMedicamento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarMedicamentoFiltro" Method="SP_ListarMedicamentoFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarMedicamentoFiltroResult">
      <Column Name="IdMedicamento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enpaque" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Presentacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FechaVencimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="viaAdministracion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Almacenamiento" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Especificacion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IdPromocion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarPromocionesFiltro" Method="SP_ListarPromocionesFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarPromocionesFiltroResult">
      <Column Name="IdPromocion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Porcentaje" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>